# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: VOLCANIZED
email: virajavimaddur@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://vmaddur.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Cards.yml
cards:
  - name: "Example Card 1"
    img: "/assets/img/laptop.svg"
    desc: "Some quick example text to build on the card title and make up the bulk of the card's content"
    modal:
      title: "Modal portfolio 1"
      body: "Modal body text goes here."
      id: portfolio-1

  - name: "Example Card 2"
    img: "/assets/img/laptop.svg"
    desc: "Some quick example text to build on the card title and make up the bulk of the card's content"
    modal:
      title: "Modal portfolio 2"
      body: "Modal body text goes here."
      id: portfolio-2

  - name: "Example Card 3"
    img: "/assets/img/laptop.svg"
    desc: "Some quick example text to build on the card title and make up the bulk of the card's content"
    modal:
      title: "Modal portfolio 3"
      body: "Modal body text goes here."
      id: portfolio-3

# Colors.yml
# Use these prebuilt options instead of seraching through the css to change the colors.
# I used the solarized colors https://en.wikipedia.org/wiki/Solarized_(color_scheme)

colors:
  main-text: "839496"
  secondary-text: "b58900"
  tertiary-text: "6c71c4"
  important-text: "268bd2"

  main-background: "002a36"
  secondary-background: "073642"
  tertiary-background: "002b36"

  main-header: "cb4b16"
  secondary-header: "859900"
  nav-header: "2aa198"

# Pages.yml

# Add your pages here!
# I have to use pagez because site.pages is already a thing.
pagez:
  - name: Home
    href: home
    file: "home.html"

  - name: About
    href: about
    file: "about.html"

  - name: Portfolio
    href: portfolio
    file: "portfolio.html"

  - name: Experience
    href: experience
    file: "experience.html"

# Social.yml
social:
  - name: facebook
    url: www.facebook.com

  - name: instagram
    url: www.instagram.com

  - name: google
    url: test@test.com

  - name: github
    url: www.github.com

  - name: twitter
    url: www.twitter.com
